### ISSUE TITLE
Tried to add to queue, crashed

### ISSUE THREAD

**Issue by Geczy** [aseylys/KStock#2]
```
Traceback (most recent call last):
  File "KStock.py", line 606, in addQueue
    _add(tick.tickEdit.text())
  File "KStock.py", line 590, in _add
    self.qTicks.append(Tick(ticker, self.purPrice.value(), self.trader))
  File "C:\Users\Matt\Documents\GitHub\KStock-1\Tick.py", line 34, in __init__
    self.update(purPrice, ah)
  File "C:\Users\Matt\Documents\GitHub\KStock-1\Tick.py", line 48, in update
    data = rCall(self.trader, self.T, ah)
  File "C:\Users\Matt\Documents\GitHub\KStock-1\resources\rHood.py", line 40, in rCall
    'YH' : round(float(tickFund['high_52_weeks']), 2),
TypeError: float() argument must be a string or a number, not 'NoneType'

```

**Comment by Geczy** [comment]
Only happens when I add `TVIX` or `SCYX`

**Comment by Geczy** [comment]
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Robinhood\Robinhood.py", line 245, in quote_data
    req.raise_for_status()
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.robinhood.com/quotes/'SCYX/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "KStock.py", line 606, in addQueue
    _add(tick.tickEdit.text())
  File "KStock.py", line 590, in _add
    self.qTicks.append(Tick(ticker, self.purPrice.value(), self.trader))
  File "C:\Users\Matt\Documents\GitHub\KStock-1\Tick.py", line 34, in __init__
    self.update(purPrice, ah)
  File "C:\Users\Matt\Documents\GitHub\KStock-1\Tick.py", line 48, in update
    data = rCall(self.trader, self.T, ah)
  File "C:\Users\Matt\Documents\GitHub\KStock-1\resources\rHood.py", line 21, in rCall
    tickQuote = trader.quote_data(stock = tick)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Robinhood\Robinhood.py", line 248, in quote_data
    raise RH_exception.InvalidTickerSymbol()
Robinhood.exceptions.InvalidTickerSymbol

**Comment by aseylys** [comment]
This seems to be more an issue with Robinhood, seeing as how it's missing data in the request, but I put in an update to catch this error.
