### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by zerowebcorp** [aseylys/KStock#7]
Hello,

I want to test this, however, having difficulty getting it up and running. I did read that it requires python 3.5. I haven't had luck setting up python on my windows machine and I've tried with Ubuntu vps from digital ocean. However, I am not quite sure how to set it up. Any help is appreciated.

Here is what I have done. Stood up a vanilla ubuntu 16 from Digital ocean.

```
apt update
add-apt-repository ppa:jonathonf/python-3.6
apt-get update
apt-get install python3.6 python3-pip
git clone https://github.com/aseylys/KStock
cd KStock
pip3 install -r requirements.txt
root@kstock:~/KStock# python3.6 KStock.py
Traceback (most recent call last):
  File "KStock.py", line 14, in <module>
    import os, datetime, pytz, holidays, json, requests, sys
ModuleNotFoundError: No module named 'pytz'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "KStock.py", line 14, in <module>
    import os, datetime, pytz, holidays, json, requests, sys
ModuleNotFoundError: No module named 'pytz'
root@kstock:~/KStock#
```

Or it needs to be executed only on a Windows machine?

**Comment by zerowebcorp** [comment]
Finally got it working on a Windows machine after downgrading Python from 3.7 to 3.5
